CREATE TABLE [dbo].[CHITIETGIAO](
	[MaDonHang] [nvarchar](10) NOT NULL,
	[MaShipper] [nvarchar](10) NOT NULL,
	[NgayGiao] [date] NULL,
	[TinhTrang] [bit] NULL,
PRIMARY KEY CLUSTERED 
(
	[MaDonHang] ASC,
	[MaShipper] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[DIACHI]    Script Date: 6/14/2019 6:49:56 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[DIACHI](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[KhuVuc] [nvarchar](20) NULL,
	[parent_id] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[DONHANG]    Script Date: 6/14/2019 6:49:56 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[DONHANG](
	[MaDonHang] [nvarchar](10) NOT NULL,
	[MaNhanVien] [int] NOT NULL,
	[TenKhachHang] [nvarchar](30) NULL,
	[SDT] [nvarchar](11) NULL,
	[Tinh] [nvarchar](20) NULL,
	[Huyen] [nvarchar](20) NULL,
	[DCChiTiet] [nvarchar](50) NULL,
	[MoTa] [nvarchar](50) NULL,
	[TienHang] [money] NULL,
	[PhiShip] [money] NULL,
	[Shipper] [nvarchar](10) NULL,
	[TongTienDonHang]  AS ([PhiShip]+[TienHang]),
PRIMARY KEY CLUSTERED 
(
	[MaDonHang] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
 CONSTRAINT [UNQ_DONHANG_MADH] UNIQUE NONCLUSTERED 
(
	[MaDonHang] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[NHANVIEN]    Script Date: 6/14/2019 6:49:56 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[NHANVIEN](
	[MaNhanVien] [int] IDENTITY(1,1) NOT NULL,
	[userpassword] [nvarchar](20) NULL,
	[TenNhanVien] [nvarchar](30) NULL,
	[SDT] [nvarchar](11) NULL,
	[NgaySinh] [date] NULL,
	[GioiTinh] [bit] NULL,
	[DiaChi] [nvarchar](50) NULL,
	[Email] [nvarchar](50) NULL,
PRIMARY KEY CLUSTERED 
(
	[MaNhanVien] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
 CONSTRAINT [UNQ_NHANVIEN_MaNhanVien] UNIQUE NONCLUSTERED 
(
	[MaNhanVien] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[SHIPPER]    Script Date: 6/14/2019 6:49:56 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[SHIPPER](
	[MaShipper] [nvarchar](10) NOT NULL,
	[TenShipper] [nvarchar](30) NULL,
	[GioiTinh] [bit] NULL,
	[Email] [nvarchar](30) NULL,
	[NgaySinh] [date] NULL,
	[SDT] [nvarchar](11) NULL,
	[KhuVucPhuTrach] [int] NULL,
	[TrangThai] [bit] NULL,
PRIMARY KEY CLUSTERED 
(
	[MaShipper] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
 CONSTRAINT [UNQ_SHIPPER_MASHIPPER] UNIQUE NONCLUSTERED 
(
	[MaShipper] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CHITIETGIAO] ADD  CONSTRAINT [DEF_CHITIETGIAO_NgayGiao]  DEFAULT (getdate()) FOR [NgayGiao]
GO
ALTER TABLE [dbo].[DONHANG] ADD  CONSTRAINT [DEF_DONHANG_TenKH]  DEFAULT (N'custommer') FOR [TenKhachHang]
GO
ALTER TABLE [dbo].[DONHANG] ADD  CONSTRAINT [DEF_DONHANG_TienHang]  DEFAULT ((0)) FOR [TienHang]
GO
ALTER TABLE [dbo].[DONHANG] ADD  CONSTRAINT [DEF_DONHANG_PhiShip]  DEFAULT ((0)) FOR [PhiShip]
GO
ALTER TABLE [dbo].[NHANVIEN] ADD  CONSTRAINT [DEFF_NHANVIEN_password]  DEFAULT (N'admin') FOR [userpassword]
GO
ALTER TABLE [dbo].[SHIPPER] ADD  CONSTRAINT [DEF_SHIPPER_TrangThai]  DEFAULT ((1)) FOR [TrangThai]
GO
ALTER TABLE [dbo].[CHITIETGIAO]  WITH CHECK ADD  CONSTRAINT [FK_CHITIETGIAO_DonHang] FOREIGN KEY([MaDonHang])
REFERENCES [dbo].[DONHANG] ([MaDonHang])
GO
ALTER TABLE [dbo].[CHITIETGIAO] CHECK CONSTRAINT [FK_CHITIETGIAO_DonHang]
GO
ALTER TABLE [dbo].[CHITIETGIAO]  WITH CHECK ADD  CONSTRAINT [FK_CHITIETGIAO_Shipper] FOREIGN KEY([MaShipper])
REFERENCES [dbo].[SHIPPER] ([MaShipper])
GO
ALTER TABLE [dbo].[CHITIETGIAO] CHECK CONSTRAINT [FK_CHITIETGIAO_Shipper]
GO
ALTER TABLE [dbo].[DONHANG]  WITH CHECK ADD  CONSTRAINT [FK_DONHANG_MaNV] FOREIGN KEY([MaNhanVien])
REFERENCES [dbo].[NHANVIEN] ([MaNhanVien])
GO
ALTER TABLE [dbo].[DONHANG] CHECK CONSTRAINT [FK_DONHANG_MaNV]
GO
ALTER TABLE [dbo].[DONHANG]  WITH CHECK ADD  CONSTRAINT [FK_DONHANG_Shipper] FOREIGN KEY([Shipper])
REFERENCES [dbo].[SHIPPER] ([MaShipper])
GO
ALTER TABLE [dbo].[DONHANG] CHECK CONSTRAINT [FK_DONHANG_Shipper]
GO
ALTER TABLE [dbo].[SHIPPER]  WITH CHECK ADD  CONSTRAINT [FK_SHIPPER_KhuVuc] FOREIGN KEY([KhuVucPhuTrach])
REFERENCES [dbo].[DIACHI] ([id])
GO
ALTER TABLE [dbo].[SHIPPER] CHECK CONSTRAINT [FK_SHIPPER_KhuVuc]
GO
ALTER TABLE [dbo].[DONHANG]  WITH CHECK ADD  CONSTRAINT [Check_DONHANG_PhiShip] CHECK  (([PhiShip]>(0)))
GO
ALTER TABLE [dbo].[DONHANG] CHECK CONSTRAINT [Check_DONHANG_PhiShip]
GO
ALTER TABLE [dbo].[DONHANG]  WITH CHECK ADD  CONSTRAINT [Check_DONHANG_TienHang] CHECK  (([TienHang]>(0)))
GO
ALTER TABLE [dbo].[DONHANG] CHECK CONSTRAINT [Check_DONHANG_TienHang]
GO
ALTER TABLE [dbo].[NHANVIEN]  WITH CHECK ADD  CONSTRAINT [Check_NHANVIEN_NgaySinh] CHECK  ((getdate()>[NgaySinh]))
GO
ALTER TABLE [dbo].[NHANVIEN] CHECK CONSTRAINT [Check_NHANVIEN_NgaySinh]
GO
ALTER TABLE [dbo].[SHIPPER]  WITH CHECK ADD  CONSTRAINT [Check_SHIPPER_NgaySinh] CHECK  ((getdate()>[NgaySinh]))
GO
ALTER TABLE [dbo].[SHIPPER] CHECK CONSTRAINT [Check_SHIPPER_NgaySinh]
GO